version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: kopherlog
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: kopherlog
      MYSQL_DATABASE: kopherlog
      MYSQL_USER: kopherlog
      MYSQL_PASSWORD: kopherlog
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: