### Post recruitment
POST http://localhost:8080/recruitments
Content-Type: application/json

{
  "recruitmentCategories": "PROJECT",
  "progressMethods": "ALL",
  "techStacks": [
    "Java",
    "Spring"
  ],
  "recruitmentPositions": [
    "BackendEngineer",
    "Infra"
  ],
  "numberOfPeople": 3,
  "progressPeriod": 3,
  "recruitmentDeadline": "2024-12-31",
  "contract": "test@test.com",
  "subject": "新しいサービス開発に携わりたい方募集",
  "content": "実はSES、笑"
}